#ifndef CPU_VARIABLES_ESTRUCTURAS_H_
#define CPU_VARIABLES_ESTRUCTURAS_H_
char * IP_CPU;
char * PUERTO_ESCUCHA_DISPATCH;
char * PUERTO_ESCUCHA_INTERRUPT;
char * IP_MEMORIA;
char * PUERTO_MEMORIA;
#endif